import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// ✅ Redux
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import GlobalAuthInitializer from "./GlobalAuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Car Rental CRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Wrap the whole app with Redux Provider */}
        <Providers>
          <Navbar />
          {/* ✅ Run user fetch logic once globally */}
          {/* <GlobalAuthInitializer /> */}
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              success: {
                style: {
                  background: "#10b981",
                  color: "white",
                  fontWeight: "500",
                },
              },
              error: {
                style: {
                  background: "#ef4444",
                  color: "white",
                  fontWeight: "500",
                },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
